### PR TITLE
Wrap-up all my wireguard changes

### PR DESCRIPTION
**Pull request by droscy**
@lhoracek, if you tested my `wireguard/main` branch and you prefer to merge all my changes in a single command, here is the PR.

I'll keep this list up to date:

- created `wireguard_status` binary sensor to check if remote peer is up
- created `wireguard_handshake` sensor to track timestamp of latest handshake
- added `peer_allowed_ips` parameter to set the list of allowd ip/mask
- added `reboot_timeout` parameter to reboot the board if remote peer is unreachable
- updated the list of codeowners
- wrapped `start_connection_()` in a `defer()` to avoid blocking setup step
- suspended (and resumed) watchdog for log dns resolution
- added compilation tests for wireguard component and sensors

### CODE REVIEW

**Comment by lhoracek** [comment]
Going to test today. You're on fire 🔥 and sorry for my late response.

**Comment by lhoracek** [comment]
Quickly skimming the changes it looks great. Will test quickly and approve.

**Review by lhoracek — APPROVED** [review]
LGTM, works fine.

**Comment by droscy** [comment]
@lhoracek I don't know how to fix the remaining CI errors.

They complain about the missing `esp_wireguard.h` file: that file is part of the external library so it isn't inside `components/wireguard/` folder, but other components that use external libraries don't have such errors (I tried running checks locally for `qr_code` and `tm1651`).

**Comment by lhoracek** [comment]
@droscy looking at it.  I will add this component to the test.yaml files as well today in the process.

**Comment by lhoracek** [comment]
I'm thinking it has to do with the `library.json` definition in the https://github.com/droscy/esp_wireguard, but I'm running into issues getting the `./script/lint_cpp` to run locally on my mac (getting `clang-tidy-11` not found even though it is on PATH). Will get back to my linux machine tomorrow.

**Comment by lhoracek** [comment]
@droscy can you take a look at this in your library.json?:
```
	 "export":{
      "include":[
         "include/*",
         "src/*"
      ]
	 },
```

Looking at the doco I'm not sure it expects the wildcard there as it should point to directory and default value is `include` -> https://docs.platformio.org/en/latest/manifests/library-json/fields/build/includedir.html

Might be the issue.

**Comment by droscy** [comment]
The snippet you reported is `export/include` [0] but the link points to `build/includeDir` [1] and both are present in library.json

```json
	 "export":{
      "include":[
         "include/*",
         "src/*"
      ]
	 },
   "build":{
      "includeDir": "include",
      "srcDir": "src"
   }
```

(and I could have removed the whole `build` as that is the default).

Maybe the wrong tab used for indenting `export`? It is however only used for package generation.
The other relevant parameter is `headers` [2] but I think of having set it correctly.

[0] https://docs.platformio.org/en/latest/manifests/library-json/fields/export/include.html
[1] https://docs.platformio.org/en/latest/manifests/library-json/fields/build/includedir.html
[2] https://docs.platformio.org/en/latest/manifests/library-json/fields/headers.html

**Comment by droscy** [comment]
Probably I've found the issue: line 35 of `platformio.ini`, I've never set there the dependecy on esp_wireguard.

**Comment by droscy** [comment]
The two checks for esp8266 boards have just failed and it is correct because wireguard is only for esp32. How can we skip those checks?

**Comment by lhoracek** [comment]
In other components I see declaring dependency:
DEPENDENCIES = ["esp32"]

As I said, I'm not able to run the clang-tidy on my daily driver. A did not
see it required to spin up some virtual environment for this yet :-/

Luboš Horáček

**Comment by droscy** [comment]
> In other components I see declaring dependency: 
> DEPENDENCIES = ["esp32"]

Great, thanks.

That dependency along with `#ifdef USE_ESP32` inside wireguard source files make all tests to succeede, except test6.yaml... but the error doesn't seem to be releted to wireguard...

**Comment by droscy** [comment]
Yes, all the automated tests succeeded.

I've added @thomas0bernard among codeowners (after his acceptance), the more the better,  bugs may arrive after official merge :-D

@lhoracek please, do some tests and if you feel confident merge to original PR. Keep an eye on the first `start_connection_()` call that has been wrapped inside `defer()` to avoid blocking the setup step as required by ESPHome guidelines, I have no issue with it and it should seed up wg initialization.

**Pull request merged**
